@ECHO OFF & TITLE TimeElapsed.bat

SETLOCAL EnableDelayedExpansion 

CALL :GETTIMEINFRACSECONDS BEGSECONDS
REM Do Stuff here here
CALL :GETELAPSED
GOTO :END

:GETTIMEINFRACSECONDS
 SET T=!TIME!
 SET OUTVARNAME=%1
 SET T=!T::0=:!
 SET T=!T:.0=.!
   FOR /F "TOKENS=1-4 DELIMS=:." %%W IN ("!T!") DO (
     SET /A %1=%%W * 360000 + %%X * 6000 + %%Y * 100 + %%Z
   )
GOTO :EOF

:GETELAPSED
 ECHO %0
   CALL :GETTIMEINFRACSECONDS ENDSECONDS
   SET ARG1=%1
   IF DEFINED ARG1 SET BEGSECONDS=!%1!
   SET /A ELAPSED=ENDSECONDS - BEGSECONDS
   SET /A WHOLES=ELAPSED / 100
   SET MILLIS=!ELAPSED:~-2!0
   IF "!ELAPSED!" LSS "0" (
      SET /A ELAPSED=ELAPSED + (24 * 360000)
      )
   ECHO TimeElapsed(Seconds.Milliseconds)=!WHOLES!.!MILLIS!
GOTO :EOF

:END
